spring:
  datasource:
    url: jdbc:mysql://localhost:3306/market_analysis
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver

aws:
  credentials:
    access-key: aaa
    secret-key: aaa
  sqs:
    new-files-queue: test

ftp:
  host: test
  port: 1111
  username: aaaa
  password: bbbb