spring:
  datasource:
    url: jdbc:mysql://localhost:3306/market_analysis
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver

aws:
  sqs:
    new-files-queue: test
