name: DEV - Deploy Lambda to aws ECS
env:
  AWS_REGION: us-east-1
  SERVICE: lambda

on: 
  workflow_dispatch:
  push:
    branches: [ "lambda" ]
  pull_request:
    branches: [ "lambda" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: checkout self
      uses: actions/checkout@v4

    - name: checkout terraform
    - uses: actions/checkout@v4
      with:
        repository: CompanyB-TeamDelta/terraform
        path: terraform

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: cd
      run: |
        cd terraform/${{ env.SERVICE }}

    - name: Setup Terraform 
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform init
      id: init
      run: terraform init

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check

    # Run a terraform validate
    - name: Terraform Validate
      id: validate
      # Run even if formatting fails
      if: success() || failure()
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -out=plan

    - name: Terraform apply
      id: apply
      env:
        TF_LOG: DEBUG
      run: terraform apply -auto-approve -input=false "plan"
